### DISCUSSION TITLE
Is there a way to read values from environment variables?

### DISCUSSION THREAD

**Discussion by ealap** [kcl-lang/kcl#1308] [Q&A] [answered]
I would like to use KCL to build a configuration file where some values depend on the current shell environment.

Currently, I work around it by using the override option
```kcl
_HOME = "HOME"
TEMPLATE_DIR = "${_HOME}/project/templates"
```

```shell
kcl run --overrides "_HOME=${HOME}" -- "/path/to/kcl/file"
```

But I worry that I may need a lot of overrides in the future once the config starts to get big. Is there something more straight forward without using override like maybe `read_env`
```
_HOME = read_env("HOME")
TEMPLATE_DIR = "${_HOME}/project/templates"
```

```shell
kcl run -- "/path/to/kcl/file"
```

**Comment by Peefy** [comment, marked as answer]
Hello @ealap . Currently, there is no such built-in function in KCL, but it can be considered to be added in the next major version v0.9.0.

**Reply by ealap** [reply]
Thank you for considering this.

**Reply by tvandinther** [reply]
I came here also looking for an answer. I'd be interested in this feature too.

My use case:

KCL plugin is configured for Argo CD and the command is fixed, but I want to inject values via the Argo CD application such as a name suffix. My intention is to use the `spec.source.plugin.env` field to add it as the value comes from the ApplicationSet generator.

**Comment by Peefy** [comment]
The env read function: https://www.kcl-lang.io/docs/reference/model/file#read_env

**Comment by liangyuanpeng** [comment]
Hi @Peefy 
Thanks you for working for it,I'm using this feature to read file for multi line string, and it's not working for me (:  
 would you want to support it? 

```main.k
import file


_str=file.read("/home/lan/kubeadm-t.yaml")

_nodes=[{
        kubeadmConfigPatches = [_str]
}
]
nodes=_nodes
```

now
```yaml
nodes:
- kubeadmConfigPatches:
  - "kind: ClusterConfiguration\netcd:\n  external:\n    endpoints: \n    - http://localhost:2379\napiServer:\n  extraArgs:\n    runtime-config: api/all=true\n    storage-media-type: application/json\n    audit-log-path: /var/log/audit/kube-apiserver-audit.log\n    audit-policy-file: /etc/kubernetes/audit-policy/apiserver-audit-policy.yaml\n  extraVolumes:\n    - name: \"audit-logs\"\n      hostPath: /var/log/audit\n      mountPath: /var/log/audit\n    - name: audit-policy\n      hostPath: /etc/kubernetes/audit-policy\n      mountPath: /etc/kubernetes/audit-policy"
```

expect
```yaml
nodes:
- kubeadmConfigPatches:
  - |
    kind: ClusterConfiguration
    etcd:
      external:
        endpoints:
        - http://localhost:2379
    apiServer:
      extraArgs:
        runtime-config: api/all=true
        storage-media-type: application/json
        audit-log-path: /var/log/audit/kube-apiserver-audit.log
        audit-policy-file: /etc/kubernetes/audit-policy/apiserver-audit-policy.yaml
      extraVolumes:
        - name: "audit-logs"
          hostPath: /var/log/audit
          mountPath: /var/log/audit
        - name: audit-policy
          hostPath: /etc/kubernetes/audit-policy
          mountPath: /etc/kubernetes/audit-policy
```
