### DISCUSSION TITLE
How do we output fields with leading underscores?

### DISCUSSION THREAD

**Discussion by cakemanny** [kcl-lang/kcl#1718] [Q&A]
Hi, how is it possible to produce a config with a leading underscore?

We want to use KCL to generate out [declarative kong configuration](https://docs.konghq.com/gateway/latest/production/deployment-topologies/db-less-and-declarative-config/#declarative-configuration-format). It fields `_format_version` and `_transform`. The `_format_version` is required.

Part of their example:
```yaml
_format_version: "3.0"
_transform: true

services:
- name: my-service
 url: https://example.com
 plugins:
 - name: key-auth
 routes:
 - name: my-route
   paths:
   - /
 ```
 
We weren't able to find anything in the docs, e.g. in https://www.kcl-lang.io/docs/user_docs/support/faq-kcl
 
We also tried a few ideas but none were working
```
schema XYZ:
    [str]: str

xyz = {
    "_foo": "bar"
    "foo": "bar"
    xyz: XYZ {
        _bla: "bla"
    }
}
```
-->
```
xyz:
  foo: bar
  xyz: {}
```

**Comment by Peefy** [comment]
You can use the `-H` flag to show this fields. e.g., `kcl main.k -H`

**Reply by diefans** [reply]
So basically, if I need leading underscores, I need to sacrifice the "hiding feature"?

**Reply by cakemanny** [reply]
So, it would mean it that it's not possible to use variables with `_` in that file in order to factor out common code anymore? And we would have to run `kcl` separately on those files.
This doesn't feel like a good solution....
Are there plans for a syntactical solution?
For reserved words we have the `$` ... seems like there should be something for this case.

**Reply by cakemanny** [reply]
I guess combining the `-H` flag with path selection, `-S`, is starting to head in the right direction, as long as I keep the underscores out of the result type schemas:

```
schema Route:
    name: str
    paths: [str]

schema Plugin:
    name: str

schema Service:
    name: str
    url: str
    plugins: [Plugin]
    routes: [Route]

schema KongConfig:
    _format_version: str
    _transform: bool
    services: [Service]

_domain = "example"

out: KongConfig = {
    _format_version = "3.0"
    _transform = True

    services = [
        {
            name = "{}-service".format(_domain)
            url = "https://{}.com".format(_domain)
            plugins = [
                {
                    name = "key-auth"
                }
            ]
            routes = [
                {
                    name = "{}-route".format(_domain)
                    paths = ["/"]
                }
            ]
        }
    ]
}
```

```
% kcl kong.k -H -S out
_format_version: '3.0'
_transform: true
services:
- name: example-service
  url: https://example.com
  plugins:
  - name: key-auth
  routes:
  - name: example-route
    paths:
    - /
```
