### DISCUSSION TITLE
Questions on optional schema parameter

### DISCUSSION THREAD

**Discussion by mihaigalos** [kcl-lang/kcl#444] [Announcements]
### 1. Minimal reproduce step (Required)

Tried to run the example from the [docs](https://kcl-lang.io/docs/user_docs/guides/configuration).
```kcl
schema Person:
    gender: "Male" | "Female"
    name: Name

schema Name:
    first: str
    middle?: str  # Optional, but must be non-empty when specified
    last: str

    check:
        first != ""
        last != ""
        middle != "" if middle

alice = Person {
    gender: "Female"
    name.first: "Alice"
    name.last: "White"
    name.middle: ""
}
```
Ran with `kcl person.k`.

### 2. What did you expect to see? (Required)
Error, since middle name is empty.

### 3. What did you see instead (Required)
```yaml
alice:
  gender: Female
  name:
    first: Alice
    last: White
    middle: ''     <-- Expected an error on this line.
```

### 4. What is your KusionStack components version? (Required)
I don't have the folder required for this step on my machine (`Kusion/kclvm-go/KCLVM`), since built the binaries from source (commit 82c2be097be0ae29b8a159171f0d379737bd3eba from March 8th).

[Playground link](http://39.106.40.108/-/play/index.html?id=9121282e53afb920fd87eb5c26d97aeaa83f3908).
