### DISCUSSION TITLE
Insert yaml fragment

### DISCUSSION THREAD

**Discussion by weironz** [kcl-lang/kcl#781] [Q&A] [answered]
is kcl support Insert yaml fragment ?

This is my configuration requirement， i want insert cni-plugins config in flannel helm chart values.yaml  initcontinaer options.

now i use shell command sed, i want know can kcl implement this configuration?

```
    cat <<EOF | sed -i '/^\s*initContainers/ r /dev/stdin' charts/flannel/templates/daemonset.yaml
      - name: install-cni-plugins
        image: docker.io/labring4docker/cni-plugins:v1.3.0
        command: ["/bin/sh"]
        args: ["-c", "cp -au /cni-plugins/* /cni-plugin/"]
        volumeMounts:
        - name: cni-plugin
          mountPath: /cni-plugin
EOF
```

the source file: https://github.com/flannel-io/flannel/blob/master/chart/kube-flannel/templates/daemonset.yaml

**Comment by Peefy** [comment]
Hi @willzhang there. Thank you for providing the information. ❤️  The first answer to your question is affirmative. 🎉

In fact, in-place mutating or validating of existing Kubernetes YAML configurations is a key capability provided by KCL. For this purpose, we propose the KRM KCL specification to carry KCL code to achieve this function. You can refer to here for more information:

+ https://github.com/kcl-lang/krm-kcl
+ https://kcl-lang.io/docs/user_docs/guides/working-with-k8s/mutate-manifests/helm-kcl-plugin

In addition, we also provide many examples on container configuration editing and validation of KCL code models here. You can refer to these examples to insert container configurations, and we also welcome contributing more models e.g., `inject-cni-plugin-sidecar`:

+ https://github.com/kcl-lang/krm-kcl/blob/main/examples/mutation/add-certificates-volume/main.k
+ https://github.com/kcl-lang/krm-kcl/blob/main/examples/mutation/add-capabilities/main.k

**Comment by Peefy** [comment]
Besides, we have offered kcl operator to mutate k8s manifests at cluster runtime. Ref: https://github.com/kcl-lang/kcl-operator

**Comment by weironz** [comment]
i can't understand how to use this examples
```
root@ubuntu:/data/git/krm-kcl/examples/mutation/add-certificates-volume# kcl main.k 
{}
root@ubuntu:/data/git/krm-kcl/examples/mutation/add-certificates-volume# kp
kpartx  kpm     
root@ubuntu:/data/git/krm-kcl/examples/mutation/add-certificates-volume# kpm  main.k 
No help topic for 'main.k'
root@ubuntu:/data/git/krm-kcl/examples/mutation/add-certificates-volume# 
```

**Comment by Peefy** [comment]
HI @willzhang, you can use this examples in the krm-kcl repo top level

```shell
cat ./examples/mutation/add-certificates-volume/suite/good.yaml | go run main.go
```

The input YAML is

```yaml
apiVersion: v1
kind: Pod
metadata:
  name: nginx
  annotations:
    inject-certs: "enabled"
spec:
  containers:
  - name: nginx
    image: nginx:1.14.2
    ports:
    - containerPort: 80
```

The output YAML is (with volumes and volumeMounts)

```yaml
apiVersion: v1
kind: Pod
metadata:
  annotations:
    inject-certs: enabled
  name: nginx
spec:
  containers:
  - image: nginx:1.14.2
    name: nginx
    ports:
    - containerPort: 80
    volumeMounts:
    - name: etc-ssl-certs
      mountPath: /etc/ssl/certs
  volumes:
  - name: etc-ssl-certs
    configMap:
      name: ca-pemstore
```

**Comment by weironz** [comment]
Thank you for your reply.

I find the good.yaml have `kind: KCLRun` part.
However, usually good.yaml is a mutated original official yaml file and the kcl section should not be inserted in advance.

Is this possible for kcl ? it's like `kustomize patch`,  but `kustomize patch` not support patch yaml if the yaml is a helm template with `{{ .Values.flannel.image.tag }}` variables, kustomize regards this as an informal yaml file.

So here are two questions: 
1、does kcl support inserting a configuration into a raw yaml file, 
2、does kcl support  mutate non standard format yaml files, such as helm chart template yaml files (Contains template syntax)

Here is a simple scenario.

part1
```
# source.yaml
apiVersion: v1
kind: Pod
metadata:
  annotations:
    inject-certs: enabled
  name: nginx
spec:
  containers:
  - image: nginx:1.14.2
    name: nginx
    ports:
    - containerPort: 80
```
part2， or maybe it's kcl lang yaml
```
# patch.yaml
  - image: docker.io/labring4docker/cni-plugins:v1.3.0
    name: install-cni-plugins
    command: ["/bin/sh"]
    args: ["-c", "cp -au /cni-plugins/* /cni-plugin/"]
```
run kcl
```
kcl run source.yaml patch.yaml
```
the results
```
# result.yaml
apiVersion: v1
kind: Pod
metadata:
  annotations:
    inject-certs: enabled
  name: nginx
spec:
  containers:
  - image: nginx:1.14.2
    name: nginx
    ports:
    - containerPort: 80
  - image: docker.io/labring4docker/cni-plugins:v1.3.0
    name: install-cni-plugins
    command: ["/bin/sh"]
    args: ["-c", "cp -au /cni-plugins/* /cni-plugin/"]
```

**Comment by Peefy** [comment, marked as answer]
If you only want to use KCL code and YAML files, this is also possible. I will write the following example to illustrate:

The kcl code (main.k)

```python
import yaml

yaml.decode(option("source", default="{}")) | {
    # Use the `+=` to patch the cni-plugin sidecar container config
    spec.containers += [
        {
            image: "docker.io/labring4docker/cni-plugins:v1.3.0"
            name: "install-cni-plugins"
            command: ["/bin/sh"]
            args: ["-c", "cp -au /cni-plugins/* /cni-plugin/"]
        }
    ]
}
```

The source yaml (source.yaml)

```yaml
apiVersion: v1
kind: Pod
metadata:
  annotations:
    inject-certs: enabled
  name: nginx
spec:
  containers:
  - image: nginx:1.14.2
    name: nginx
    ports:
    - containerPort: 80
```

Run the following command

```shell
kcl main.k -D source="$(cat source.yaml)" -o output.yaml
```

The output yaml (output.yaml)

```yaml
apiVersion: v1
kind: Pod
metadata:
  annotations:
    inject-certs: enabled
  name: nginx
spec:
  containers:
  - image: nginx:1.14.2
    name: nginx
    ports:
    - containerPort: 80
  - image: docker.io/labring4docker/cni-plugins:v1.3.0
    name: install-cni-plugins
    command:
    - /bin/sh
    args:
    - -c
    - cp -au /cni-plugins/* /cni-plugin/
```
