### ISSUE TITLE
[Enhancement] GitHub Action supports building and testing as KCL on macos-arm64 and Linux arch64 systems.

### ISSUE THREAD

**Issue by Peefy** [kcl-lang/kcl#1015]
## Enhancement

+ [ ] macos arm64 CI using the self-hosted runner

```yaml
name: Build and Test on macOS ARM64

on: [push, pull_request]

jobs:
  build-and-test:
    runs-on: [self-hosted, macos-arm64] # or macos-12-xlarge
    steps:
    - uses: actions/checkout@v3
    - name: Build and test
      run: |
         ....
```

+ [ ] linux arch64 CI using QEMU with the builder image `kcllang/kcl-builder-arm64`

```yaml

name: Build and Test on Linux AARCH64

on: [push, pull_request]

jobs:
  build-and-test:
    runs-on: ubuntu-20.04
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
        with:
          platforms: linux/amd64,linux/arm64/v8
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Run custom ARM64 Docker image
        run: |
          docker run --rm --platform linux/arm64/v8 \
            -v ${{ github.workspace }}:/workspace -w /workspace \
            kcllang/kcl-builder-arm64 \
            make
        ..
```

**Comment by baoyachi** [comment]
Recommended: https://github.com/cross-rs/cross.

E.g: [build-cross](https://github.com/strawlab/iana-time-zone/blob/0c4c1596484eb1d3870542f635cc22609dd82e45/.github/workflows/rust.yml#L111-L140)

**Comment by Peefy** [comment]
> Recommended: https://github.com/cross-rs/cross.
> 
> E.g: [build-cross](https://github.com/strawlab/iana-time-zone/blob/0c4c1596484eb1d3870542f635cc22609dd82e45/.github/workflows/rust.yml#L111-L140)

Thank you! @baoyachi I'll try it. However, I have found that it also relies on QEMU, and I have not found any support for macos arm64 in CI. If you have any other ideas, please feel free to share them.

**Comment by baoyachi** [comment]
Also see this: https://github.blog/2023-10-02-introducing-the-new-apple-silicon-powered-m1-macos-larger-runner-for-github-actions/

E.g:https://github.com/openvinotoolkit/openvino/blob/2ae120f8f1f89cbaddc0c741c2ce1c5af293a5c4/.github/workflows/mac.yml#L67

**Comment by Peefy** [comment]
> Also see this: https://github.blog/2023-10-02-introducing-the-new-apple-silicon-powered-m1-macos-larger-runner-for-github-actions/
> 
> E.g:https://github.com/openvinotoolkit/openvino/blob/2ae120f8f1f89cbaddc0c741c2ce1c5af293a5c4/.github/workflows/mac.yml#L67

Thank you! I've noticed the `macos-13-arm64` runner. https://github.com/actions/runner-images/blob/main/images/macos/macos-13-arm64-Readme.md

Unfortunately, it does not have a `macos-12-arm64` runner. 😂

**Comment by UtkarshUmre** [comment]
Hey @Peefy  I am new to KCL and learning. I came across this good first issue that I would like to work on. Could you please assign this issue to me and guide me a little bit?

**Comment by Peefy** [comment]
> Hey @Peefy I am new to KCL and learning. I came across this good first issue that I would like to work on. Could you please assign this issue to me and guide me a little bit?

Thank you! @UtkarshUmre The purpose of this issue is to build a CI script for compiling KCL in a Linux arm64 environment using the `kclang/kcl-builder-arm64` image.

**Comment by UtkarshUmre** [comment]
What I understand is that we need to compile the KCL language code during the continuous integration phase itself in a `Linux ARM64` environment, using the `kclang/kcl-builder-arm64` image. However, what should be the right approach to do this? It would be really helpful if you could point me to specific resources

**Comment by Peefy** [comment]
> What I understand is that we need to compile the KCL language code during the continuous integration phase itself in a `Linux ARM64` environment, using the `kclang/kcl-builder-arm64` image. However, what should be the right approach to do this? It would be really helpful if you could point me to specific resources

@UtkarshUmre You can add CI scripts as follows using QEMU and the arm docker image:

```yaml
  build-and-test-arm64:
    name: Test
    runs-on: ubuntu-latest
    steps:
      # QEMU enables you run arm64 image on x86 machines
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
        with:
          platforms: linux/arm64
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Run custom ARM64 Docker image
        run: |
          docker run --rm \
            -v ${{ github.workspace }}:/workspace -w /workspace \
            kcllang/kcl-builder-arm64 \
            make && make release
      - uses: actions/upload-artifact@v3
        with:
          name: kcl-linux-arm64
          path: _build/dist/ubuntu/kclvm

```
