### ISSUE TITLE
Unexpected scheme default value behaviour

### ISSUE THREAD

**Issue by bozaro** [kcl-lang/kcl#1037]
## Bug Report

Looks like it is not possible to set the attribute value if the schema has declared the default attribute value.

### 1. Minimal reproduce step (Required)

```
schema Foo:
    a: {str:str} = {"name": "test"}
    b: [int] = [1, 2, 3]

foo = Foo {
    a: {"one": "two"}
    b: [42]
}
```

### 2. What did you expect to see? (Required)
I expect to see values:
```yaml
foo:
  a:
    one: two
  b:
  - 42
```

### 3. What did you see instead (Required)
For this scheme, the explicit value of each field in the `foo` structure is set, but nevertheless the values flow from the description of the structure.

```yaml
foo:
  a:
    name: test
    one: two
  b:
  - 42
  - 2
  - 3
```

### 4. What is your KCL components version? (Required)
```
kcl version
0.7.5-linux-amd64
```
