### ISSUE TITLE
__settings__ key in output when iterating over object of schema type

### ISSUE THREAD

**Issue by vtomilov** [kcl-lang/kcl#1060]
## Bug Report

It seems that `__settings__` is showing in output where it shouldn't be. The example is simple, but I'm facing issues when I try to iterate over an object of schema type and have to use clauses like `if key != "__settings__"` in KCL code.

### 1. Minimal reproduce step (Required)

```
schema Item:
    value: str

schema Items:
    [str]: Item

_data = Items {
    "a": {value: 'foo'}
    "b": {value: 'bar'}
}

r = [[k, v] for k, v in _data]
```

### 2. What did you expect to see? (Required)

```
r:
- - a
  - value: foo
- - b
  - value: bar
```
### 3. What did you see instead (Required)
```
r:
- - __settings__
  - output_type: INLINE
- - a
  - value: foo
- - b
  - value: bar
```
### 4. What is your KCL components version? (Required)
KCL playground for v0.7.0, in v0.7.5 it also reproduces.
