### ISSUE TITLE
Unexpected dictionary mutation

### ISSUE THREAD

**Issue by bozaro** [kcl-lang/kcl#1172]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

```
cat <<EOF > example.k && kclvm_cli run example.k
x = {
    a = 1
    b = True
}
y = {
    c = 3
    d = "4"
}
z = {"foo":i for i in [x, y]}.foo
EOF
```

### 2. What did you expect to see? (Required)

`x` value contains exactly two elements.
```
x:
  a: 1
  b: true
y:
  c: 3
  d: '4'
z:
  a: 1
  b: true
  c: 3
  d: '4'
```

### 3. What did you see instead (Required)

Values from `y` is merged to `x` dictionary.

```
x:
  a: 1
  b: true
  c: 3
  d: '4'
y:
  c: 3
  d: '4'
z:
  a: 1
  b: true
  c: 3
  d: '4'
```

### 4. What is your KCL components version? (Required)

Checked on:
 - kcl 0.8.4-linux-amd64
 - kclvm_cli main (https://github.com/kcl-lang/kcl/commit/ff86214a872172f9329da11c4e3ab5dd4f1834ce)
