### ISSUE TITLE
GetSchemaType(Mapping) does not list schemas without identifier

### ISSUE THREAD

**Issue by patrycju** [kcl-lang/kcl#1250]
## Bug Report

When schema instances are created without identifier (e.g. as an element of list or without assigning it to any name), they are ignored by GetSchemaType and GetSchemaTypeMapping functions.

### 1. Minimal reproduce step (Required)

KCL file:
```
paths = ["./hello", "./world"]

schema Dir:
    path: str

tmpDir = Dir {
    path = "/tmp/sometemp"
}

Dir { path = "/tmp/tmp" }

hello_dirs = [Dir { path = p } for p in paths]
```

```
result, _ := kcl.RunFiles([]string{"dirs.k"})
schema, _ := kcl.GetSchemaTypeMapping("dirs.k", "", "")

fmt.Println(result.First().YAMLString())

for k, v := range schema {
    fmt.Println(k, v)
}
```

### 2. What did you expect to see? (Required)

```
hello_dirs:
    - path: ./hello
    - path: ./world
path: /tmp/tmptmp
paths:
    - ./hello
    - ./world
tmpDir:
    path: /tmp/sometemp

Dir type:"schema"  schema_name:"Dir"  properties:{key:"path"  value:{type:"str"  line:1}}  required:"path"  filename:"/Users/patrycjusz/Workspace/iceberg/ice/manifests/dirs.k"  pkg_path:"__main__"
tmpDir type:"schema"  schema_name:"Dir"  properties:{key:"path"  value:{type:"str"  line:1}}  required:"path"  filename:"/Users/patrycjusz/Workspace/iceberg/ice/manifests/dirs.k"  pkg_path:"__main__"

# Object without assigned name
type:"schema"  schema_name:"Dir"  properties:{key:"path"  value:{type:"str"  line:1}}  required:"path"  filename:"/Users/patrycjusz/Workspace/iceberg/ice/manifests/dirs.k"  pkg_path:"__main__"

# Objects located in hello_dirs:
type:"schema"  schema_name:"Dir"  properties:{key:"path"  value:{type:"str"  line:1}}  required:"path"  filename:"/Users/patrycjusz/Workspace/iceberg/ice/manifests/dirs.k"  pkg_path:"__main__"
type:"schema"  schema_name:"Dir"  properties:{key:"path"  value:{type:"str"  line:1}}  required:"path"  filename:"/Users/patrycjusz/Workspace/iceberg/ice/manifests/dirs.k"  pkg_path:"__main__"

```

### 3. What did you see instead (Required)

```
hello_dirs:
    - path: ./hello
    - path: ./world
paths:
    - ./hello
    - ./world
tmpDir:
    path: /tmp/sometemp

Dir type:"schema"  schema_name:"Dir"  properties:{key:"path"  value:{type:"str"  line:1}}  required:"path"  filename:"/Users/patrycjusz/Workspace/iceberg/ice/manifests/dirs.k"  pkg_path:"__main__"
tmpDir type:"schema"  schema_name:"Dir"  properties:{key:"path"  value:{type:"str"  line:1}}  required:"path"  filename:"/Users/patrycjusz/Workspace/iceberg/ice/manifests/dirs.k"  pkg_path:"__main__"

```

### 4. What is your KCL components version? (Required)

KCL go SDK v0.8.5
