### ISSUE TITLE
Check with `regex.match()` evaluated before "required attribute missing"

### ISSUE THREAD

**Issue by excalq** [kcl-lang/kcl#1337]
## Bug Report

When a schema contains a check, using `regex.match(attribute ...)`, this appears to be evaluated before the existence of a non-optional attribute in the instantiated object.

If the required attribute is absent, a compiler error is thrown regarding the schema's `check regex.match(attribute)` itself, rather than notification that the user's object is lacking a required attribute. The more obvious error would be raising that the attribute is missing (`attribute .. is required and can't be None or Undefined`).

As it were, the current error causes a user to debug a problem with the `check`. In my case the missing field was in an inherited schema's object, compounding my confusion.

The reproduction will easily illustrate this.

### 1. Minimal reproduce step (Required)

[Playground Link](http://101.42.3.224/-/play/index.html?id=32bb991fc4edc15f78b0d0d524cb45f202bce3cf)
```
import regex

schema CrossplaneResource:
  name: str
  description: str
  check:
    regex.match(description, "[a-zA-Z0-9+=,.@-_]"), "Description must match the regex [a-zA-Z0-9+=,.@-_]"

ice: CrossplaneResource = {
  name: 'Vanilla Ice'
  # description: 'Ice Ice Baby' # Works with this field uncommented
}
```

### 2. What did you expect to see? (Required)

The missing field should fail with an error before the check dies on the missing `description` variable.

```
EvaluationError
  --> /tmp/sandbox1241309759/prog.k:15:1
   |
15 |   name: 'Vanilla Ice'
   |  attribute 'description' of CrossplaneResource is required and can't be None or Undefined
   |
```

### 3. What did you see instead (Required)

```
EvaluationError
  --> /tmp/sandbox1225202080/prog.k:11:1
   |
11 |     regex.match(description, "[a-zA-Z0-9+=,.@-_]"), "Description must match the regex [a-zA-Z0-9+=,.@-_]"
   |  match() missing 2 required positional arguments: 'string' and 'pattern'
   |
```

### 4. What is your KCL components version? (Required)

0.8.7-darwin-arm64
