### ISSUE TITLE
bug in adding to list

### ISSUE THREAD

**Issue by steeling** [kcl-lang/kcl#1400]
```bash
kcl version
0.8.9-darwin-arm64
```
input:
```
schema x:
    m: [str] = ["hello"]

s = x {
}

t = s | {
    m += ["world"]
}
```

outputs

```
s:
  m:
  - hello
t:
  m:
  - hello
  - hello
  - world
```

expected:

```
s:
  m:
  - hello
t:
  m:
  - hello
  - world
```
