### ISSUE TITLE
Have not get the | - +  from """

### ISSUE THREAD

**Issue by liangyuanpeng** [kcl-lang/kcl#1407]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

```
kind = "Cluster"
apiVersion = "kind.x-k8s.io/v1alpha4"
networking = {
     #https://kcl-lang.io/docs/user_docs/support/faq-kcl#39-how-to-set-default-value-for-option-function-in-kcl
    apiServerAddress = option("apiaddress",default="127.0.0.1")
}
nodes=[{
        role = "control-plane",
        image = option("kindimage",default="kindest/node:v1.30.0")
        kubeadmConfigPatches = [
            """
        kind: ClusterConfiguration
        apiServer:
        extraArgs:
            runtime-config: api/all=true 
            storage-media-type: option("storageMediaType",default="application/json")
        """
        ]
}]
qqq="""
kind: ClusterConfiguration
apiServer:
extraArgs:
    runtime-config: api/all=true 
    storage-media-type: option("storageMediaType",default="application/json")
"""
qqq2="""
hello
"""
```

I'm try to using kcl to manage kind config files and have not get the `|` from `kubeadmConfigPatches`.

```
$ kcl main.k 
kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
networking:
  apiServerAddress: '127.0.0.1'
nodes:
- role: control-plane
  image: kindest/node:v1.30.0
  kubeadmConfigPatches:
  - "\n        kind: ClusterConfiguration\n        apiServer:\n        extraArgs:\n            runtime-config: api/all=true \n            storage-media-type: option(\"storageMediaType\",default=\"application/json\")\n        "
qqq: "\nkind: ClusterConfiguration\napiServer:\nextraArgs:\n    runtime-config: api/all=true \n    storage-media-type: option(\"storageMediaType\",default=\"application/json\")\n"
qqq2: |2

  hello
```

### 2. What did you expect to see? (Required)

```yaml
$ kcl main.k 
kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
networking:
  apiServerAddress: '127.0.0.1'
nodes:
- role: control-plane
  image: kindest/node:v1.30.0
  kubeadmConfigPatches:
  - |
    kind: ClusterConfiguration
    apiServer:
      extraArgs:
        runtime-config: api/all=true 
        storage-media-type: application/json
...
```

I'm not sure kcl does support this case? remind me if i missed something,Thanks.
