### ISSUE TITLE
[Enhancement] Enhance the completion experience of KCL Import for both internal and external packages

### ISSUE THREAD

**Issue by Peefy** [kcl-lang/kcl#1429]
## Enhancement

For the following module

```python
.
├── kcl.mod
├── kcl.mod.lock
├── main.k
└── tt
    └── tt.k
```

The content of `kcl.mod` is

```toml
[package]
name = "m"
edition = "v0.9.0"
version = "0.0.1"

[dependencies]
k8s = { oci = "oci://ghcr.io/kcl-lang/k8s", tag = "1.29" }
```

The import stmt in `main.k` should be enhanced

![image](https://github.com/kcl-lang/kcl/assets/22744597/62daafe7-5a3c-4142-ab43-ef1d55afd439)

The completion items should contains `tt` and `k8s`
