### ISSUE TITLE
Adding Elements in with conditional does not work as expected 

### ISSUE THREAD

**Issue by karlderkaefer** [kcl-lang/kcl#1658]
## Bug Report

I have problems to use arrays with conditionals. I would like add an element to an array, but the output is not as expected. Not sure if only primitive types are supported in arrays

### 1. Minimal reproduce step (Required)

```kcl
# Define schemas
schema PolicyStatement:
    Sid: str
    Effect: str
    Action: [str]
    Resource: [str]

schema PolicyDocument:
    Version: str = "2012-10-17"
    Statement: [PolicyStatement]

_s3_statement = PolicyStatement {
    Sid = "AllowS3Read"
    Effect = "Allow"
    Action = [
        "s3:GetObject"
        "s3:GetObjectVersion"
        "s3:ListBucket"
        "s3:ListBucketVersions"
    ]
    Resource = ["arn:aws:s3:::mybucket/*"]
}

_statement_custom_key_1 = PolicyStatement {
    Sid = "AllowKMSDecryptCustomKey"
    Effect = "Allow"
    Action = ["kms:Decrypt"]
    Resource = ["arn:aws:kms:::alias/custom-key"]
}

_statement_custom_key_2: PolicyStatement = PolicyStatement {
    Sid = "AllowKMSDecryptCustomKey2"
    Effect = "Allow"
    Action = ["kms:Decrypt"]
    Resource = ["arn:aws:kms:::alias/custom-key2"]
}

_statements: [PolicyStatement] = [_s3_statement]

if False:
    _statements += [_statement_custom_key_1]
if True:
    _statements += [_statement_custom_key_2]

items = [
    PolicyDocument {
        Statement = _statements
    }
]
 ```

### 2. What did you expect to see? (Required)

```yaml
items:
- Version: '2012-10-17'
  Statement:
  - Sid: AllowS3Read
    Effect: Allow
    Action:
    - s3:GetObject
    - s3:GetObjectVersion
    - s3:ListBucket
    - s3:ListBucketVersions
    Resource:
    - arn:aws:s3:::mybucket/*
  - Sid: AllowKMSDecryptCustomKey2
    Effect: Allow
    Action:
    - kms:Decrypt
    Resource:
    - arn:aws:kms:::alias/custom-key2
```

### 3. What did you see instead (Required)

```yaml
items:
- Version: '2012-10-17'
  Statement:
  - Sid: AllowS3Read
    Effect: Allow
    Action:
    - s3:GetObject
    - s3:GetObjectVersion
    - s3:ListBucket
    - s3:ListBucketVersions
    Resource:
    - arn:aws:s3:::mybucket/*
  - Sid: AllowKMSDecryptCustomKey2
    Effect: Allow
    Action:
    - kms:Decrypt
    Resource:
    - arn:aws:kms:::alias/custom-key2
  - Sid: AllowKMSDecryptCustomKey2
    Effect: Allow
    Action:
    - kms:Decrypt
    Resource:
```

### 4. What is your KCL components version? (Required)

kcl --version
kcl version 0.9.4

**Comment by karlderkaefer** [comment]
It seem to work with work with latest version 0.10.0 im doing some more tests in crossplane
```
kcl demo.k
items:
- Version: '2012-10-17'
  Statement:
  - Sid: AllowS3Read
    Effect: Allow
    Action:
    - s3:GetObject
    - s3:GetObjectVersion
    - s3:ListBucket
    - s3:ListBucketVersions
    Resource:
    - arn:aws:s3:::mybucket/*
  - Sid: AllowKMSDecryptCustomKey2
    Effect: Allow
    Action:
    - kms:Decrypt
    Resource:
    - arn:aws:kms:::alias/custom-key2
  ```
