### ISSUE TITLE
[bug] mixin degradation from 0.9 to 0.10

### ISSUE THREAD

**Issue by dennybaa** [kcl-lang/kcl#1668]
Hello, @Peefy hope you are doing well.

I've noticed a weird behavior which certainly looks like a bug:

```
protocol StringProtocol:
    s: str

mixin StringMixin for StringProtocol:
    add = lambda pref: str {
        pref + s
    }

schema String:
    mixin [StringMixin]
    s: str
    add: (str) -> str

s1 = String { s: "hello" }
s2 = String { s: "world" }

output = {
    s1_add: s1.add("foo ")
    s2_add: s2.add("foo ")
}
```

Produces:

```
s1:
  s: hello
s2:
  s: world
output:
  s1_add: foo world
  s2_add: foo world
```

Though there should've been `foo hello` and `foo world`, in other words we get a singleton mixin function set by the latest type initiation.
