### ISSUE TITLE
multi-file compilation using print outputs '{}' at the end of the output file

### ISSUE THREAD

**Issue by haskjold** [kcl-lang/kcl#1670]
### 1. Minimal reproduce step (Required)

Cut & paste the example here and run it: https://www.kcl-lang.io/docs/reference/lang/tour#multi-file-compilation

### 2. What did you expect to see? (Required)

```yaml
apiVersion: v1
kind: Deployment
metadata:
  name: model1
  labels:
    key1: value1
    key2: value2
  annotations:
    key: value
spec:
  minReadySeconds: 0
  paused: false
  progressDeadlineSeconds: 600
  replicas: 2
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      key1: value1
      key2: value2
---
apiVersion: v1
kind: Deployment
metadata:
  name: model2
spec:
  minReadySeconds: 0
  paused: false
  progressDeadlineSeconds: 600
  replicas: 3
  revisionHistoryLimit: 10
  selector: {}
```

### 3. What did you see instead (Required)

```yaml
apiVersion: v1
kind: Deployment
metadata:
  name: model1
  labels:
    key1: value1
    key2: value2
  annotations:
    key: value
spec:
  minReadySeconds: 0
  paused: false
  progressDeadlineSeconds: 600
  replicas: 2
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      key1: value1
      key2: value2
---
apiVersion: v1
kind: Deployment
metadata:
  name: model2
spec:
  minReadySeconds: 0
  paused: false
  progressDeadlineSeconds: 600
  replicas: 3
  revisionHistoryLimit: 10
  selector: {}

{}
```

### 4. What is your KCL components version? (Required)

```
$ kcl version
0.10.0-linux-amd64
```
