### ISSUE TITLE
Performance issue: top-level field value evaluated twice

### ISSUE THREAD

**Issue by bozaro** [kcl-lang/kcl#1759]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

kcl run for file:
```
show = lambda s -> str {
    print("show: ${s}")
    s
}

foo = _foo

_foo = {
    name: "foo"
    value: show("foo")
}

_bar = {
    name: "bar"
    value: show("bar")
}

bar = _bar
```

### 2. What did you expect to see? (Required)
I expect single `show: foo` and `show: bar` lines:
```
show: foo
show: bar
foo:
  name: foo
  value: foo
bar:
  name: bar
  value: bar
```

### 3. What did you see instead (Required)
```
show: foo
show: foo
show: bar
foo:
  name: foo
  value: foo
bar:
  name: bar
  value: bar
```

### 4. What is your KCL components version? (Required)
```
0.10.9-linux-amd64
```

**Comment by bozaro** [comment]
kcl run
```
_i = {
    _c = 0
}

show = lambda s -> str {
    _c = _i._c
    _i._c = _c + 1
    print("show: ${_c}")
    "${_c}"
}

foo2 = foo
foo1 = foo
foo = {
    name: "foo"
    value: show("foo")
}
```
Output:
```
show: 0
show: 1
foo2:
  name: foo
  value: '0'
foo1:
  name: foo
  value: '0'
foo:
  name: foo
  value: '1'
```
