### ISSUE TITLE
New CIDR functions not working as expected

### ISSUE THREAD

**Issue by maulik13** [kcl-lang/kcl#1857]
## Bug Report

### 1. Minimal reproduce step (Required)

I downloaded the latest release v0.11.1 and I copied the kcl file from test and I  two CIDR functions, hosts_in_CIDR and subnets_from_CIDR, are not working. 

I ran `kcl run main.k` on the following configuration,
```kcl
import net

cidr0 = net.parse_CIDR("192.168.1.0/24")
cidr1 = net.hosts_in_CIDR("192.168.1.0/24")
cidr2 = net.subnets_from_CIDR("192.168.1.0/24")
cidr3 = net.is_IP_in_CIDR("192.168.1.1", "192.168.1.0/24")
cidr4 = net.is_IP_in_CIDR("192.168.0.1", "192.168.1.0/24")
```

And here is my output.
```yaml
cidr0:
  ip: '192.168.1.0'
  mask: 24
cidr1: []
cidr2: []
cidr3: true
cidr4: false                                                                                                                                                                                                                                                                             
```

### 2. What did you expect to see? (Required)

I should see cidr1 and cidr2 not to be empty. I am not sure what will be the exact values since that is what I was trying to figure out. 

### 3. What did you see instead (Required)

Empty values for `cidr1` and `cidr2`

### 4. What is your KCL components version? (Required)

Downloaded the binary from GitHub release v0.11.1
```
Version: 0.11.1-c020ab3eb4b9179219d6837a57f5d323
Platform: aarch64-apple-darwin
GitCommit: d8964b29170ba28c98a31b561a2d9525112d1f30
```
