### ISSUE TITLE
KCL vet command doesn't work on schemas which import other KCL Packages

### ISSUE THREAD

**Issue by anshuishere** [kcl-lang/kcl#1877]
### 1. Minimal reproduce step 
```
# Create a KCL Schema which depends on other KCL Package

import microserviceA.schema as msA
import micorserviceB.schema as msB

Schema TopLevel:
    microserviceA: msA.schema
    microserviceB. msB.schema


Where microservices are any kcl pages you include as dependencies

# Do a KCL validation

kcl vet config.yaml top-level-schema.k --forat yaml

It will fail because KCL vet will not make KCL pull the required deps or even resolve it from local cache in .kpm
```

### 2. What did you expect to see? 
```
kcl vet works because I can do kcl run and it executes everything.
```

### 3. What did you see instead 
```
kcl vet fails
```

### 4. What is your KCL components version? 
0.10.10-linux-amd64

**Comment by He1pa** [comment]
I tried with
a.k
```
import b

schema Person:
    name: b.Name    
```

b.k
```
schema Name:
    name: str
```

a.yaml
```
name:
  name: "a"
```

`kcl vet a.yaml a.k --format yaml`

It worked for me on v0.11.1

![Image](https://github.com/user-attachments/assets/1827b234-c2ba-4752-9b24-c30b4c887498)

Can you test with latest version and provide more details?

**Comment by anshuishere** [comment]
Let me show you an example!

I created a new KCL package called "a"

```
# cat kcl.mod
[package]
name = "a"
edition = "v0.11.0"
version = "0.0.1"

[dependencies]
k8s = { oci = "oci://ghcr.io/kcl-lang/k8s", tag = "1.31.2" }

# My schema.k
import k8s.api.apps.v1
schema MySchema: 
    myPodYaml: v1.Deployment

# I created a yaml to validate
myPodYaml:
   apiVersion: apps/v1
   kind: Deployment
   metadata:
     labels:
       app: mydeploy
     name: mydeploy
   spec:
     replicas: 1
     selector:
       matchLabels:
         app: mydeploy
     template:
       metadata:
         labels:
           app: mydeploy
       spec:
         containers:
         - image: myimage
           name: myimage
```

Now when I do validation

![Image](https://github.com/user-attachments/assets/61cb5b1d-12d9-44a8-b3dc-3c9c6f8bfd1c)

However kcl run command works perfectly fine

![Image](https://github.com/user-attachments/assets/a898a3cd-3488-4630-96d5-c645898c76f7)

Here is the content of main.k
```
import yaml
import file

_filepath_input = option("input-file-path",type='str', required=True,default="myYaml.yaml")
_file_input = yaml.decode(file.read(_filepath_input))

myConig = MySchema{
    **_file_input
}
```
