### ISSUE TITLE
[Enhancement] Top level config unification backward reference.

### ISSUE THREAD

**Issue by Peefy** [kcl-lang/kcl#247]
## Enhancement

For the following KCL code (test.k):

```
schema Data:
    name: str
    version?: str

data1: Data {
    name = data2.name
}

data2: Data {
    name = "1"
    version = version
}

# Global version
version = "v0.1.0"
```

I want to get the expected YAML data:

```yaml
data1:
  name: '1'
data2:
  name: '1'
  version: v0.1.0
version: v0.1.0
```

Instead of the error message:

```
KCL Compile Error[E2L23] : A complie error occurs during compiling
---> File test.k:5:12
5 |    name = data2.name
           12 ^  -> Failure
name 'data2' is not defined
```
