### ISSUE TITLE
[Enhancement] KCL serialized data supports optional type fields to assist in deserialization

### ISSUE THREAD

**Issue by Peefy** [kcl-lang/kcl#654]
## Enhancement

For the following code, we need to support the optional feature to return the `@type` meta field to help users for their deserialization such as go struct.

The expect output YAML for the following code is

```python
schema Person:
    name: str = "Alice"
    age: int = 18

p = Person {}
```

```yaml
p:
  name: Alice
  age: int
  '@type': Person
```
