### ISSUE TITLE
[Bug] Invalid config mutual reference output.

### ISSUE THREAD

**Issue by Peefy** [kcl-lang/kcl#816]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

Write the following kcl code (main.k)

```python
deployment = {
    metadata.labels.k = "v"
    metadata.namespace = "default"
    spec.selector.matchLabels = metadata.labels
}
```

### 2. What did you expect to see? (Required)

```
kcl main.k
```

```yaml
deployment:
  metadata:
    labels:
      k: v
    namespace: default
  spec:
    selector:
      matchLabels:
        k: v
```

### 3. What did you see instead (Required)

```yaml
deployment:
  metadata:
    labels:
      k: v
    namespace: default
  spec:
    selector: {}  # Error output
```

### 4. What is your KCL components version? (Required)

```shell
0.7.0-alpha.1
```
