### ISSUE TITLE
kcl import will generate invalid file

### ISSUE THREAD

**Issue by ShiroDN** [kcl-lang/kcl#947]
I am new to KCL, so I was just trying to learn how to work with KCL. I am attempting to import a kubernetes config map that has a literal block scalar aka way to include a text file in configmap. However, there seems to be an issue when processing these blocks with kcl import. If I try to generate yaml from a .k file, it results in InvalidSyntax errors. When you look at the generated .k file.

Tested on KCL version 0.7.0-linux-amd64.

#### 1.  cm.yaml file
```yaml
---
# Source: filebeat/templates/configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: release-name-filebeat-daemonset-config
  labels:
    app: "release-name-filebeat"
    chart: "filebeat-8.5.1"
    heritage: "Helm"
    release: "release-name"
data:
  filebeat.yml: |
    filebeat.inputs:
    - type: container
      paths:
        - /var/log/containers/*.log
      processors:
      - add_kubernetes_metadata:
          host: ${NODE_NAME}
          matchers:
          - logs_path:
              logs_path: "/var/log/containers/"
    
    output.elasticsearch:
      host: '${NODE_NAME}'
      hosts: '["https://${ELASTICSEARCH_HOSTS:elasticsearch-master:9200}"]'
      username: '${ELASTICSEARCH_USERNAME}'
      password: '${ELASTICSEARCH_PASSWORD}'
      protocol: https
      ssl.certificate_authorities: ["/usr/share/filebeat/certs/ca.crt"]
---
```
#### 2. `$ kcl import -f cm.yaml` will result in this cm.k file

```
"""
This file was generated by the KCL auto-gen tool. DO NOT EDIT.
Editing this file might prove futile when you re-run the KCL auto-gen generate command.
"""

apiVersion = "v1"
kind = "ConfigMap"
metadata = {
    name = "release-name-filebeat-daemonset-config"
    labels = {
        app = "release-name-filebeat"
        chart = "filebeat-8.5.1"
        heritage = "Helm"
        release = "release-name"
    }
}
data = {
    "filebeat.yml" = "filebeat.inputs:
    - type: container
      paths:
        - /var/log/containers/*.log
      processors:
      - add_kubernetes_metadata:
          host: ${NODE_NAME}
          matchers:
          - logs_path:
              logs_path: "/var/log/containers/"
    
    output.elasticsearch:
      host: '${NODE_NAME}'
      hosts: '["https://${ELASTICSEARCH_HOSTS:elasticsearch-master:9200}"]'
      username: '${ELASTICSEARCH_USERNAME}'
      password: '${ELASTICSEARCH_PASSWORD}'
      protocol: https
      ssl.certificate_authorities: ["/usr/share/filebeat/certs/ca.crt"]
    "
}
```

#### 3. Running `$ kcl cm.k` will result in InvalidSyntax errors

```
Error: error[E1001]: InvalidSyntax
  --> /home/tomas/cm.k:18:22
   |
18 |     "filebeat.yml" = "filebeat.inputs:
   |                      ^ unterminated string
   |
.
.
.
```
